// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/Mrpye/helm-api"
        },
        "license": {
            "name": "Apache 2.0 licensed",
            "url": "https://github.com/Mrpye/helm-api/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Check API Endpoint",
                "operationId": "check-api-endpoint",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/add_repo": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "add a helm chart repo",
                "operationId": "add-helm-chart-repo",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.ImportChartRepo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "charts Repo Added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/create_ns": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Create Namespace",
                "operationId": "create-namespace",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.NamespaceChartRepo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "namespace created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get_config": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "get the config for helm chart",
                "operationId": "get-helm-chart-config",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.GetPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/body_types.InstallUpgradeRequest"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get_config_install": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "get the config for helm chart and installs",
                "operationId": "get-helm-chart-config-install",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.GetPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/body_types.InstallUpgradeRequest"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get_config_upgrade": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "get the config for helm chart and installs",
                "operationId": "get-helm-chart-config-upgrade",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.GetPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "chart installed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get_ip": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get Service IP",
                "operationId": "get-service-ip",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.GetServiceIP"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/body_types.ServiceDetails"
                            }
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/install": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Install a helm chart",
                "operationId": "install-helm-chart",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.InstallUpgradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "chart installed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/uninstall": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "uninstall a helm chart",
                "operationId": "uninstall-helm-chart",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.UninstallChartRepo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "chart uninstalled",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upgrade": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Upgrade a helm chart",
                "operationId": "upgrade-helm-chart",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/body_types.InstallUpgradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "chart upgraded",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "body_types.GetPayload": {
            "type": "object",
            "properties": {
                "answer_file": {
                    "type": "string"
                },
                "config": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "release_name": {
                    "type": "string"
                }
            }
        },
        "body_types.GetServiceIP": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "release_name": {
                    "type": "string"
                }
            }
        },
        "body_types.ImportChartRepo": {
            "type": "object",
            "properties": {
                "repo": {
                    "type": "string"
                },
                "repo_name": {
                    "type": "string"
                }
            }
        },
        "body_types.InstallUpgradeRequest": {
            "type": "object",
            "properties": {
                "chart": {
                    "type": "string"
                },
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "namespace": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "release_name": {
                    "type": "string"
                }
            }
        },
        "body_types.NamespaceChartRepo": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                }
            }
        },
        "body_types.ServiceDetails": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "service_type": {
                    "type": "string"
                }
            }
        },
        "body_types.UninstallChartRepo": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "release_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "helm-api",
	Description:      "Helm-api is a CLI application written in Golang that gives the ability to perform Install, Uninstall and Upgrade Helm Charts via Rest API endpoint. The application can be run as a stand alone application or deployed as a Container. Also for convenience there is the  ability to create namespaces and retrieve service IPs of the deployed application. GitHub repository at https://github.com/Mrpye/helm-api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
